### ISSUE TITLE
only authorize source

### ISSUE THREAD

**Issue by andres-garcia-ATX** [stitchdata/stitch-js#11]
@iterati 

I have tried using the "only-authorize" feature committed on Oct. 25th, 2018 and the pop up window closes right after signing in to the 3rd party (Facebook Ads in my case). The authorization is not truly saved on Stitch. The UI shows an error as attached: 
![image](https://user-images.githubusercontent.com/50889965/58133248-0a2f9e00-7be9-11e9-82c9-164a6a5da281.png)

I believe the storage of authorization in Stitch takes place after the pop up windows returns from the 3rd party, an account ID is selected and the "Check and Save" button is clicked. 
Remark: on this click, Stitch automatically allows the selection of tables/schema which defeats the purpose of this feature.

I don't believe an "only-authorize" feature can be truly implemented as intended unless the "Check and Save" can be manually clicked, and automatically trigger/click the "skip this step for now" hyperlink in the following page (Choose Your Data) to prevent the ability of selecting streams/schemas.

**Comment by iterati** [comment]
Andres,

Facebook and Google, both AdWords and Analytics, require an additional step after the OAuth step to configure the connection prior to getting to field and table selection. This is the profile selections step. Profile IDs are returned by an endpoint at the third-party's site. These profiles are required to know what data to extract as a single user who logs in via OAuth might have multiple profiles available.

During the development of this feature, it was known that sources with a profile selection step were not going to work with the ONLY_AUTHORIZE feature, but it was neglected to be documented. The clients that were using FB and Google sources were not using ONLY_AUTHORIZE and the client that requested ONLY_AUTHORIZE does not require FB or Google sources.

I am unaware of any plans to extend stitch-js to support those connection types with ONLY_AUTHORIZE at this time, but will have a discussion with our product team to see if it can be addressed

Thank you.

**Comment by andres-garcia-ATX** [comment]
Thanks for the update @iterati ! I appreciate the confirmation on the status of this feature and your prompt reply.
